### ISSUE TITLE
Getting Unknown VDF_VERSION all of a sudden

### ISSUE THREAD

**Issue by FlyveHest** [EhsanKia/keypirinha-plugins#13]
I'm guessing Steam must have updated something along the way, because suddenly the Steam plugin doesn't work anymore, and I am getting this error in the log.

```
2023-02-11 18:24:06.386 [E] Error from Steam.Steam.on_catalog: <class 'ValueError'>: Unknown VDF_VERSION: 0x07564428
Traceback (most recent call last):
  File "C:\Program Files\Utils\Keypirinha\portable\Profile\InstalledPackages\Steam.keypirinha-package\steam.py", line 64, in on_catalog
  File "C:\Program Files\Utils\Keypirinha\portable\Profile\InstalledPackages\Steam.keypirinha-package\steam.py", line 143, in get_applist
  File "C:\Program Files\Utils\Keypirinha\portable\Profile\InstalledPackages\Steam.keypirinha-package\lib\appinfo.py", line 29, in load
  File "C:\Program Files\Utils\Keypirinha\portable\Profile\InstalledPackages\Steam.keypirinha-package\lib\appinfo.py", line 42, in loads
  File "C:\Program Files\Utils\Keypirinha\portable\Profile\InstalledPackages\Steam.keypirinha-package\lib\appinfo.py", line 102, in decode
```

I'm not sure what game its trying to index when it fails, so I can't supply more information or a VDF file

**Comment by EhsanKia** [comment]
Hmm I'm getting the same error too. Will take a look tonight.

**Comment by FlyveHest** [comment]
Found a C# project that has updated to the new format, looks like they have added some binary hashes to an entry.

https://github.com/SteamDatabase/SteamAppInfo/commit/b1715faba87fbbc8cb56e8fe30c92ae6ed499aab

**Comment by EhsanKia** [comment]
This is the library I use, seems like they have an open bug for it:
https://github.com/leovp/steamfiles/issues/22

I'll try to fix upstream and then update my extension too

**Comment by EhsanKia** [comment]
Actually, looks like most people are switching to this instead:
https://github.com/ValvePython/steam/blob/master/steam/utils/appcache.py

**Comment by EhsanKia** [comment]
Pushed a new version, can you see if it works now?

**Comment by FlyveHest** [comment]
Looks like the same error still

```
2023-02-11 20:13:25.366 [E] Error from Steam.Steam.on_catalog: <class 'ValueError'>: Unknown VDF_VERSION: 0x07564428
Traceback (most recent call last):
  File "C:\Program Files\Utils\Keypirinha\portable\Profile\InstalledPackages\Steam.keypirinha-package\steam.py", line 64, in on_catalog
  File "C:\Program Files\Utils\Keypirinha\portable\Profile\InstalledPackages\Steam.keypirinha-package\steam.py", line 143, in get_applist
  File "C:\Program Files\Utils\Keypirinha\portable\Profile\InstalledPackages\Steam.keypirinha-package\lib\appinfo.py", line 29, in load
  File "C:\Program Files\Utils\Keypirinha\portable\Profile\InstalledPackages\Steam.keypirinha-package\lib\appinfo.py", line 42, in loads
  File "C:\Program Files\Utils\Keypirinha\portable\Profile\InstalledPackages\Steam.keypirinha-package\lib\appinfo.py", line 102, in decode
```

Was the package built correctly?  Looks like it still contains appinfo.py which, as far as I can see, is not in the src folder anymore

**Comment by EhsanKia** [comment]
Hmm, the issue is likely on your end? If I download the bundle and unzip it, I definitely no longer see appinfo.py in library. Make sure you installed it properly and there isn't another version (like an unpacked one) overriding it.

**Comment by FlyveHest** [comment]
Very strange, I tried downloading it again, and from a incognito browser session, and when renaming to zip and opening, this is what is in the lib folder

![image](https://user-images.githubusercontent.com/55623/218277689-e17e43a4-cada-49ea-af49-63dd771f3ea0.png)

**Comment by EhsanKia** [comment]
Are you sure you're getting it from head?
https://github.com/EhsanKia/keypirinha-plugins/raw/master/keypirinha-steam/build/Steam.keypirinha-package

![image](https://user-images.githubusercontent.com/1619970/218277812-c6d67cb8-6c70-480d-8354-a2d4c2861c70.png)

**Comment by FlyveHest** [comment]
When I get it from here, https://github.com/EhsanKia/keypirinha-plugins/raw/master/keypirinha-steam/build/Steam.keypirinha-package its the old file, but if I get it from the commithistory, https://github.com/EhsanKia/keypirinha-plugins/raw/f46a6c5605a4f779ec389c482e87343c4b91829f/keypirinha-steam/build/Steam.keypirinha-package its the correct file, and it works.

So it must be some GitHub shenanigans :)

Anyways, the new version works, I have my Steam library in Keypirinha again, thanks so much for the swift response. 👍
