### ISSUE TITLE
Steam: Error from Steam.Steam.on_catalog: <class 'KeyError'>: (b'clienticon',)

### ISSUE THREAD

**Issue by tollyx** [EhsanKia/keypirinha-plugins#6]
```
17:18:54.105 ** ERROR: Error from Steam.Steam.on_catalog: <class 'KeyError'>: (b'clienticon',)
Traceback (most recent call last):
  File "C:\tools\Keypirinha\portable\Profile\InstalledPackages\Steam.keypirinha-package\steam.py", line 57, in on_catalog
  File "C:\tools\Keypirinha\portable\Profile\InstalledPackages\Steam.keypirinha-package\steam.py", line 146, in get_applist
```
I'm getting no results from the plugin due to this.

Wether the actual app actually has an icon or not in my library doesn't seem to be related, as I tried uninstalling the only game (tool, SteamVR Performance test) that had an missing icon.

**Comment by EhsanKia** [comment]
Interesting. Pushed a new version, can you see if that fixes it?

**Comment by tollyx** [comment]
Yup, that fixed it. Thanks!
